name: Make cpp.json and README

on:
  push:
    paths:
      - '**.cpp'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Run assemble.py
        run: python3 scripts/assemble.py
      - name: Run auto_readme_update.py
        run: python3 scripts/auto_readme_update.py > README.md
      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          author_name: tony9402
          author_email: tony9402@naver.com
          message: '[Auto UPD] Make cpp.json'
          add:
            - 'cpp.json'
            - 'README.md'
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

